tabWidth: 2
useTabs: false
printWidth: 80
semi: true
singleQuote: true

jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
arrowParens: always

trailingComma: all
endOfLine: lf
plugins: ['prettier-plugin-tailwindcss']
