name = "zkdrop"
main = "src/index.ts"
compatibility_date = "2026-05-20"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "../dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 3, period = 60 }

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "zkdrop-files"

[[d1_databases]]
binding = "DB"
database_name = "zkdrop-db"
database_id = "da47f71e-bc6a-4270-a9ec-a7baa73fce5d"

[triggers]
crons = ["0 0 * * *"]

[observability]
enabled = true

[observability.logs]
invocation_logs = true